### PR TITLE
Header props

### PR DESCRIPTION
**Pull request by brian-armstrong**
This PR builds on top of the user-defined header length PR from February

This allows user control of header mod/fec as well as soft demod for header and payload. This greatly improves the versatility of the flexframe object.

It'd be great to do gmsk like this too but after tinkering with it I must admit I can't figure out how to perform soft demod with gmsk.

### CODE REVIEW

**Comment by knud** [comment]
Anything come of this PR? I don't really need 14 bytes and was thinking of doing the same thing, but happily found your PR.

**Comment by brian-armstrong** [comment]
Well, quiet makes full use of this already. It works perfectly for my purposes, though it appears it does need rebased. I seem to remember the conflicts aren't particularly bad.

**Comment by knud** [comment]
My reason for looking at this is to move a project that started in GNU Radio away from it. I have several elements that are not supported in liquid-dsp and have been thinking of my own fork if I can be allowed to add at least some of them. Shorter header is one thing, LDPC is another... I had a look at quiet and maybe I should start there(?)

**Comment by brian-armstrong** [comment]
quiet is a sound modem on top of liquid. you probably don't want that :)

regarding ldpc, i'd love an implementation. i made my own libfec alternative at https://github.com/quiet/libcorrect and was hoping to get to ldpc or turbo codes but so far haven't made it there yet. soft demod viterbi + RS is pretty good but ldpc would be amazing

**Comment by knud** [comment]
Yes, I saw that (quiet), but the liquid-dsp part is all I would want.

(quiet is interesting to me regardless, but only personally :)

I have the 802.11n quasi-cyclic LDPC encoding up and running, but C++ and Eigen based, which may or may not be cool. Also, it's work for a customer, so I would have to get them to let me post it. I see no problem as it's all public domain anyway, based on published papers, etc. I plan to ask, so will let you know (eventually).

**Comment by brian-armstrong** [comment]
If you just want to try my branch of liquid that includes this PR (and my other PRs) then look at https://github.com/quiet/liquid-dsp/tree/devel

**Comment by knud** [comment]
Groovy, will do.

**Comment by jgaeddert** [comment]
My original concept was to keep the header static; it includes information for how to decode the payload, and because it's supposed to be highly protected (robust modulation/coding) it would be useful to allow the user to include a few bytes of data there. But I have gotten a lot of requests to make the header run-time adjustable. It does make debugging a bit harder, but is useful for a lot of folks.

**Pull request merged**
