### PR TITLE
dispatch to correct destroy call for fec objects

### PR DESCRIPTION
**Pull request by brian-armstrong**
free ALL the things

### CODE REVIEW

**Comment by brian-armstrong** [comment]
This patch also corrects a bug in the existing implementation

**Comment by brian-armstrong** [comment]
@jgaeddert If you're fixing memory issues, this should be an easy PR to review, and it fixes a couple :)

**Comment by jgaeddert** [comment]
Thanks for this, @brian-armstrong. I think the FEC module probably needs a pretty significant rewrite to incorporate more coding types, but I'm happy to receive any improvements like this, particularly if there are memory leaks. I really need to run valgrind against these with a bit more rigor.

**Comment by brian-armstrong** [comment]
@jgaeddert 

FWIW, at the time of writing this patch, quiet appeared to have a clean bill of health under Valgrind once I applied this patch. The codepath is basically the framegen/framesync objects so at least everything called by those appears to free correctly.

And as for more modes, I couldn't complain if turbo codes or ldpc were available :P But more practically, I think the only thing I've really wanted were smaller powers of 2 for RS, e.g RS 255,239 or maybe even 255,251

**Pull request merged**
