### PR TITLE
firdecim/firinterp: fix filter length in _create_kaiser

### PR DESCRIPTION
**Pull request by nowls**

### CODE REVIEW

**Comment by JayKickliter** [comment]
At first glance it might not be obious how this fixes anything. Can you provide a summary?

**Comment by nowls** [comment]
In `firdecim`, a Kaiser-windowed filter prototype is created based on a decimation factor `_M` and delay `_m` that determine the number of filter coefficients `h_len`.

https://github.com/jgaeddert/liquid-dsp/blob/4d851ee0282644f465626180e3ec93292ee81cba/src/filter/src/firdecim.c#L108-L112

However, when the filter taps are passed to the generic factory function, the last coefficient is omitted:

https://github.com/jgaeddert/liquid-dsp/blob/4d851ee0282644f465626180e3ec93292ee81cba/src/filter/src/firdecim.c#L121

This has the unfortunate effect of making the filter coefficients asymmetric, and hence phase linearity of the filter response is lost.

A similar description applies to the Kaiser prototype factory function in `firinterp`:

https://github.com/jgaeddert/liquid-dsp/blob/4d851ee0282644f465626180e3ec93292ee81cba/src/filter/src/firinterp.c#L115

This PR passes `h_len` on to the factory function in both objects.

**Comment by JayKickliter** [comment]
I knew this all at one time and your excellent description brought it back, thanks!

**Comment by TehWan** [comment]
Over a year later, this has not been merged yet. Is there any reason?

**Pull request merged**
